<?php

namespace App\Models\Sip;

use Illuminate\Database\Eloquent\Model;

class SipEndpoint extends Model
{
    protected $connection = 'asterisk';

    public $incrementing = false;
    public $timestamps = false;

    protected $table = 'ps_endpoints';

    protected $fillable = [
        'id',
        'transport',
        'aors',
        'auth',
        'context',
        'disallow',
        'allow',
        'direct_media',
        'deny',
        'permit',
        'mailboxes',
    ];

    // protected $attributes = [
    //     'connected_line_method'              => 'invite',
    //     'direct_media_method'                => 'invite',
    //     'direct_media_glare_mitigation'      => 'none',
    //     'disable_direct_media_on_nat'        => 'yes',
    //     'dtmf_mode'                          => 'rfc4733',
    //     'external_media_address'             => '186.64.123.211',
    //     'force_rport'                        => 'yes',
    //     'ice_support'                        => 'yes',
    //     'identify_by'                        => 'username',
    //     'moh_suggest'                        => 'default',
    //     'outbound_auth'                      => '102',
    //     'outbound_proxy'                     => '0',
    //     'rewrite_contact'                    => 'yes',
    //     'rtp_ipv6'                           => '0',
    //     'rtp_symmetric'                      => '1',
    //     'send_diversion'                     => 'yes',
    //     'send_pai'                           => 'no',
    //     'send_rpid'                          => 'no',
    //     'timers_min_se'                      => '90',
    //     'timers'                             => 'yes',
    //     'timers_sess_expires'                => '1800',
    //     'callerid'                           => '104',
    //     'callerid_privacy'                   => 'allowed_not_screened',
    //     'callerid_tag'                       => '0',
    //     '100rel'                             => 'yes',
    //     'aggregate_mwi'                      => '1',
    //     'trust_id_inbound'                   => '0',
    //     'trust_id_outbound'                  => '0',
    //     'use_ptime'                          => '0',
    //     'use_avpf'                           => '0',
    //     'media_encryption'                   => 'no',
    //     'inband_progress'                    => '0',
    //     'call_group'                         => '0',
    //     'pickup_group'                       => '0',
    //     'named_call_group'                   => '0',
    //     'named_pickup_group'                 => '0',
    //     'device_state_busy_at'               => '0',
    //     'fax_detect'                         => '0',
    //     't38_udptl'                          => '0',
    //     't38_udptl_ec'                       => 'none',
    //     't38_udptl_maxdatagram'              => '0',
    //     't38_udptl_nat'                      => '0',
    //     't38_udptl_ipv6'                     => '0',
    //     'tone_zone'                          => '0',
    //     'language'                           => '0',
    //     'one_touch_recording'                => '0',
    //     'record_on_feature'                  => 'automixmon',
    //     'record_off_feature'                 => 'automixmon',
    //     'rtp_engine'                         => 'asterisk',
    //     'allow_transfer'                     => 'yes',
    //     'allow_subscribe'                    => '1',
    //     'sdp_owner'                          => '186.64.123.211',
    //     'sdp_session'                        => 'Asterisk',
    //     'tos_audio'                          => '0',
    //     'tos_video'                          => '0',
    //     'sub_min_expiry'                     => '0',
    //     'from_domain'                        => '0',
    //     'from_user'                          => '0',
    //     'mwi_from_user'                      => 'no',
    //     'dtls_verify'                        => '0',
    //     'dtls_rekey'                         => '0',
    //     'dtls_cert_file'                     => '0',
    //     'dtls_private_key'                   => '0',
    //     'dtls_cipher'                        => '0',
    //     'dtls_ca_file'                       => '0',
    //     'dtls_ca_path'                       => '0',
    //     'dtls_setup'                         => 'actpass',
    //     'srtp_tag_32'                        => 'no',
    //     'media_address'                      => '0',
    //     'redirect_method'                    => 'user',
    //     'set_var'                            => '0',
    //     'cos_audio'                          => '0',
    //     'cos_video'                          => '0',
    //     'message_context'                    => '0',
    //     'force_avp'                          => '0',
    //     'media_use_received_transport'       => '1',
    //     'accountcode'                        => '0',
    //     'user_eq_phone'                      => '0',
    //     'moh_passthrough'                    => '1',
    //     'media_encryption_optimistic'        => '0',
    //     'rpid_immediate'                     => '0',
    //     'g726_non_standard'                  => '0',
    //     'rtp_keepalive'                      => '0',
    //     'rtp_timeout'                        => '0',
    //     'rtp_timeout_hold'                   => '0',
    //     'bind_rtp_to_media_address'          => '0',
    //     'voicemail_extension'                => '0',
    //     'mwi_subscribe_replaces_unsolicited' => '0',
    //     'deny'                               => '0',
    //     'permit'                             => '0',
    //     'acl'                                => '0',
    //     'contact_deny'                       => '0',
    //     'contact_permit'                     => '0',
    //     'contact_acl'                        => '1',
    //     'subscribe_context'                  => '0',
    //     'fax_detect_timeout'                 => '0',
    //     'contact_user'                       => '0',
    //     'preferred_codec_only'               => '0',
    //     'asymmetric_rtp_codec'               => '0',
    //     'rtcp_mux'                           => '0',
    //     'allow_overlap'                      => '1',
    //     'refer_blind_progress'               => '0',
    //     'notify_early_inuse_ringing'         => '0',
    //     'max_audio_streams'                  => '0',
    //     'max_video_streams'                  => '0',
    //     'webrtc'                             => '1',
    //     'dtls_fingerprint'                   => '1',
    //     'incoming_mwi_mailbox'               => '1',
    //     'bundle'                             => '0',
    //     'dtls_auto_generate_cert'            => '1',
    //     'follow_early_media_fork'            => '1',
    //     'accept_multiple_sdp_answers'        => 'yes',
    //     'suppress_q850_reason_headers'       => 'SHA-256',
    //     'trust_connected_line'               => '0',
    //     'send_connected_line'                => '1',
    //     'ignore_183_without_sdp'             => 'no',
    //     'codec_prefs_incoming_offer'         => '1',
    //     'codec_prefs_outgoing_offer'         => '0',
    //     'codec_prefs_incoming_answer'        => '1',
    //     'codec_prefs_outgoing_answer'        => '0',
    //     'send_history_info'                  => 'yes',
    //     'allow_unauthenticated_options'      => 'yes',
    //     't38_bind_udptl_to_media_address'    => '0',
    //     'geoloc_incoming_call_profile'       => 'prefer:pending, operation:intersect, keep:all, transcode:allow',
    //     'geoloc_outgoing_call_profile'       => 'prefer:pending, operation:union, keep:all, transcode:allow',
    //     'incoming_call_offer_pref'           => 'prefer:pending, operation:intersect, keep:all, transcode:allow',
    //     'outgoing_call_offer_pref'           => 'prefer:pending, operation:union, keep:all, transcode:allow',
    //     'stir_shaken_profile'                => '0',
    //     'security_negotiation'               => '0',
    //     'security_mechanisms'                => '0',
    //     'send_aoc'                           => '0',
    //     'overlap_context'                    => '0',
    //     'tenantid'                           => 'local',
    //     'suppress_moh_on_sendonly'           => 'remote_merge',
    // ];

    protected $keyType = 'int';
}
