<?php

namespace App\Models\Sip;

use Illuminate\Database\Eloquent\Model;

class SipEndpoint extends Model
{
    protected $connection = 'asterisk';

    public $incrementing = false;
    public $timestamps = false;

    protected $table = 'ps_endpoints';

    protected $fillable = [
        'id',
        'transport',
        'aors',
        'auth',
        'context',
        'disallow',
        'allow',
        'direct_media',
        'deny',
        'permit',
        'mailboxes',
        'connected_line_method',
        'direct_media_method',
        'direct_media_glare_mitigation',
        'disable_direct_media_on_nat',
        'dtmf_mode',
        'external_media_address',
        'force_rport',
        'ice_support',
        'identify_by',
        'moh_suggest',
        'outbound_auth',
        'outbound_proxy',
        'rewrite_contact',
        'rtp_ipv6',
        'rtp_symmetric',
        'send_diversion',
        'send_pai',
        'send_rpid',
        'timers_min_se',
        'timers',
        'timers_sess_expires',
        'callerid',
        'callerid_privacy',
        'callerid_tag',
        '100rel',
        'aggregate_mwi',
        'trust_id_inbound',
        'trust_id_outbound',
        'use_ptime',
        'use_avpf',
        'media_encryption',
        'inband_progress',
        'call_group',
        'pickup_group',
        'named_call_group',
        'named_pickup_group',
        'device_state_busy_at',
        'fax_detect',
        't38_udptl',
        't38_udptl_ec',
        't38_udptl_maxdatagram',
        't38_udptl_nat',
        't38_udptl_ipv6',
        'tone_zone',
        'language',
        'one_touch_recording',
        'record_on_feature',
        'record_off_feature',
        'rtp_engine',
        'allow_transfer',
        'allow_subscribe',
        'sdp_owner',
        'sdp_session',
        'tos_audio',
        'tos_video',
        'sub_min_expiry',
        'from_domain',
        'from_user',
        'mwi_from_user',
        'dtls_verify',
        'dtls_rekey',
        'dtls_cert_file',
        'dtls_private_key',
        'dtls_cipher',
        'dtls_ca_file',
        'dtls_ca_path',
        'dtls_setup',
        'srtp_tag_32',
        'media_address',
        'redirect_method',
        'set_var',
        'cos_audio',
        'cos_video',
        'message_context',
        'force_avp',
        'media_use_received_transport',
        'accountcode',
        'user_eq_phone',
        'moh_passthrough',
        'media_encryption_optimistic',
        'rpid_immediate',
        'g726_non_standard',
        'rtp_keepalive',
        'rtp_timeout',
        'rtp_timeout_hold',
        'bind_rtp_to_media_address',
        'voicemail_extension',
        'mwi_subscribe_replaces_unsolicited',
        'acl',
        'contact_deny',
        'contact_permit',
        'contact_acl',
        'subscribe_context',
        'fax_detect_timeout',
        'contact_user',
        'preferred_codec_only',
        'asymmetric_rtp_codec',
        'rtcp_mux',
        'allow_overlap',
        'refer_blind_progress',
        'notify_early_inuse_ringing',
        'max_audio_streams',
        'max_video_streams',
        'webrtc',
        'dtls_fingerprint',
        'incoming_mwi_mailbox',
        'bundle',
        'dtls_auto_generate_cert',
        'follow_early_media_fork',
        'accept_multiple_sdp_answers',
        'suppress_q850_reason_headers',
        'trust_connected_line',
        'send_connected_line',
        'ignore_183_without_sdp',
        'codec_prefs_incoming_offer',
        'codec_prefs_outgoing_offer',
        'codec_prefs_incoming_answer',
        'codec_prefs_outgoing_answer',
        'send_history_info',
        'allow_unauthenticated_options',
        't38_bind_udptl_to_media_address',
        'geoloc_incoming_call_profile',
        'geoloc_outgoing_call_profile',
        'incoming_call_offer_pref',
        'outgoing_call_offer_pref',
        'stir_shaken_profile',
        'security_negotiation',
        'security_mechanisms',
        'send_aoc',
        'overlap_context',
        'tenantid',
        'suppress_moh_on_sendonly',
    ];

    public static function getDefaultValues(){

        return [
            'connected_line_method' => 'invite',
            'direct_media_method' => 'invite',
            'direct_media_glare_mitigation' => 'none',
            'disable_direct_media_on_nat' => 'yes',
            'dtmf_mode' => 'rfc4733',
            'external_media_address' => '',
            'force_rport' => 'yes',
            'ice_support' => 'yes',
            'identify_by' => 'username',
            'moh_suggest' => 'default',
            'outbound_auth' => '',
            'outbound_proxy' => '',
            'rewrite_contact' => 'yes',
            'rtp_ipv6' => 'no',
            'rtp_symmetric' => 'no',
            'send_diversion' => 'yes',
            'send_pai' => 'no',
            'send_rpid' => 'no',
            'timers_min_se' => 90,
            'timers' => 'yes',
            'timers_sess_expires' => 1800,
            'callerid' => '',
            'callerid_privacy' => 'allowed_not_screened',
            'callerid_tag' => '',
            '100rel' => 'yes',
            'aggregate_mwi' => 'yes',
            'trust_id_inbound' => 'no',
            'trust_id_outbound' => 'no',
            'use_ptime' => 'no',
            'use_avpf' => 'no',
            'media_encryption' => 'no',
            'inband_progress' => 'no',
            'call_group' => '',
            'pickup_group' => '',
            'named_call_group' => '',
            'named_pickup_group' => '',
            'device_state_busy_at' => 0,
            'fax_detect' => 'no',
            't38_udptl' => 'no',
            't38_udptl_ec' => 'none',
            't38_udptl_maxdatagram' => 0,
            't38_udptl_nat' => 'no',
            't38_udptl_ipv6' => 'no',
            'tone_zone' => '',
            'language' => '',
            'one_touch_recording' => 'no',
            'record_on_feature' => '',
            'record_off_feature' => '',
            'rtp_engine' => 'asterisk',
            'allow_transfer' => 'yes',
            'allow_subscribe' => 'yes',
            'sdp_owner' => '',
            'sdp_session' => '',
            'tos_audio' => '',
            'tos_video' => '',
            'sub_min_expiry' => 0,
            'from_domain' => '',
            'from_user' => '',
            'mwi_from_user' => '',
            'dtls_verify' => 'no',
            'dtls_rekey' => '',
            'dtls_cert_file' => '',
            'dtls_private_key' => '',
            'dtls_cipher' => '',
            'dtls_ca_file' => '',
            'dtls_ca_path' => '',
            'dtls_setup' => 'actpass',
            'srtp_tag_32' => 'no',
            'media_address' => '',
            'redirect_method' => 'user',
            'set_var' => '',
            'cos_audio' => 0,
            'cos_video' => 0,
            'message_context' => '',
            'force_avp' => 'no',
            'media_use_received_transport' => 'no',
            'accountcode' => '',
            'user_eq_phone' => 'no',
            'moh_passthrough' => 'no',
            'media_encryption_optimistic' => 'no',
            'rpid_immediate' => 'no',
            'g726_non_standard' => 'no',
            'rtp_keepalive' => 0,
            'rtp_timeout' => 0,
            'rtp_timeout_hold' => 0,
            'bind_rtp_to_media_address' => 'no',
            'voicemail_extension' => '',
            'mwi_subscribe_replaces_unsolicited' => 'no',
            'acl' => '',
            'contact_deny' => '',
            'contact_permit' => '',
            'contact_acl' => '',
            'subscribe_context' => '',
            'fax_detect_timeout' => 0,
            'contact_user' => '',
            'preferred_codec_only' => 'no',
            'asymmetric_rtp_codec' => 'no',
            'rtcp_mux' => 'no',
            'allow_overlap' => 'no',
            'refer_blind_progress' => 'no',
            'notify_early_inuse_ringing' => 'no',
            'max_audio_streams' => 1,
            'max_video_streams' => 1,
            'webrtc' => 'yes',
            'dtls_fingerprint' => 'SHA-256',
            'incoming_mwi_mailbox' => '',
            'bundle' => 'yes',
            'dtls_auto_generate_cert' => 'no',
            'follow_early_media_fork' => 'no',
            'accept_multiple_sdp_answers' => 'no',
            'suppress_q850_reason_headers' => 'no',
            'trust_connected_line' => 'no',
            'send_connected_line' => 'no',
            'ignore_183_without_sdp' => 'no',
            'codec_prefs_incoming_offer' => 'prefer:pending, operation:intersect, keep:all, transcode:allow',
            'codec_prefs_outgoing_offer' => 'prefer:pending, operation:union, keep:all, transcode:allow',
            'codec_prefs_incoming_answer' => 'prefer:pending, operation:intersect, keep:all, transcode:allow',
            'codec_prefs_outgoing_answer' => 'prefer:pending, operation:union, keep:all, transcode:allow',
            'send_history_info' => 'no',
            'allow_unauthenticated_options' => 'no',
            't38_bind_udptl_to_media_address' => 'no',
            'geoloc_incoming_call_profile' => '',
            'geoloc_outgoing_call_profile' => '',
            'incoming_call_offer_pref' => 'local',
            'outgoing_call_offer_pref' => 'remote_merge',
            'stir_shaken_profile' => '',
            'security_negotiation' => 'no',
            'security_mechanisms' => '',
            'send_aoc' => 'no',
            'overlap_context' => '',
            'tenantid' => '',
            'suppress_moh_on_sendonly' => 'no',
        ];
    }

    protected $keyType = 'string';
}
