<?php

namespace App\Models\Sip;

use Illuminate\Database\Eloquent\Model;

class SipEndpoint extends Model
{
    protected $connection = 'asterisk';

    public $incrementing = false;
    public $timestamps = false;

    protected $table = 'ps_endpoints';

    protected $fillable = [
        'id',
        'transport',
        'aors',
        'auth',
        'context',
        'disallow',
        'allow',
        'direct_media',
        'deny',
        'permit',
        'mailboxes',
    ];

    protected $attributes = [
        'connected_line_method'              => 'invite',
        'direct_media_method'                => 'invite',
        'direct_media_glare_mitigation'      => 'none',
        'disable_direct_media_on_nat'        => 'yes',
        'dtmf_mode'                          => 'rfc4733',
        'external_media_address'             => '186.64.123.211',
        'force_rport'                        => 'yes',
        'ice_support'                        => 'yes',
        'identify_by'                        => 'username',
        'moh_suggest'                        => 'default',
        'outbound_auth'                      => '102',
        'outbound_proxy'                     => '',
        'rewrite_contact'                    => 'yes',
        'rtp_ipv6'                           => 'false',
        'rtp_symmetric'                      => 'true',
        'send_diversion'                     => 'yes',
        'send_pai'                           => 'no',
        'send_rpid'                          => 'no',
        'timers_min_se'                      => '90',
        'timers'                             => 'yes',
        'timers_sess_expires'                => '1800',
        'callerid'                           => '104',
        'callerid_privacy'                   => 'allowed_not_screened',
        'callerid_tag'                       => '',
        '100rel'                             => 'yes',
        'aggregate_mwi'                      => 'true',
        'trust_id_inbound'                   => 'false',
        'trust_id_outbound'                  => 'false',
        'use_ptime'                          => 'false',
        'use_avpf'                           => 'false',
        'media_encryption'                   => 'no',
        'inband_progress'                    => 'false',
        'call_group'                         => '',
        'pickup_group'                       => '',
        'named_call_group'                   => '0',
        'named_pickup_group'                 => 'false',
        'device_state_busy_at'               => '0',
        'fax_detect'                         => 'false',
        't38_udptl'                          => 'false',
        't38_udptl_ec'                       => 'none',
        't38_udptl_maxdatagram'              => '0',
        't38_udptl_nat'                      => 'false',
        't38_udptl_ipv6'                     => 'false',
        'tone_zone'                          => '',
        'language'                           => '',
        'one_touch_recording'                => 'false',
        'record_on_feature'                  => 'automixmon',
        'record_off_feature'                 => 'automixmon',
        'rtp_engine'                         => 'asterisk',
        'allow_transfer'                     => 'yes',
        'allow_subscribe'                    => 'true',
        'sdp_owner'                          => '186.64.123.211',
        'sdp_session'                        => 'Asterisk',
        'tos_audio'                          => '0',
        'tos_video'                          => '0',
        'sub_min_expiry'                     => '0',
        'from_domain'                        => '',
        'from_user'                          => '',
        'mwi_from_user'                      => 'no',
        'dtls_verify'                        => '0',
        'dtls_rekey'                         => '',
        'dtls_cert_file'                     => '',
        'dtls_private_key'                   => '',
        'dtls_cipher'                        => '',
        'dtls_ca_file'                       => '',
        'dtls_ca_path'                       => '',
        'dtls_setup'                         => 'actpass',
        'srtp_tag_32'                        => 'no',
        'media_address'                      => '',
        'redirect_method'                    => 'user',
        'set_var'                            => '',
        'cos_audio'                          => '0',
        'cos_video'                          => '0',
        'message_context'                    => '',
        'force_avp'                          => 'false',
        'media_use_received_transport'       => 'true',
        'accountcode'                        => '',
        'user_eq_phone'                      => 'false',
        'moh_passthrough'                    => 'true',
        'media_encryption_optimistic'        => 'false',
        'rpid_immediate'                     => 'false',
        'g726_non_standard'                  => 'false',
        'rtp_keepalive'                      => '0',
        'rtp_timeout'                        => '0',
        'rtp_timeout_hold'                   => '0',
        'bind_rtp_to_media_address'          => 'false',
        'voicemail_extension'                => '0',
        'mwi_subscribe_replaces_unsolicited' => '0',
        'deny'                               => '',
        'permit'                             => '',
        'acl'                                => '0',
        'contact_deny'                       => '',
        'contact_permit'                     => 'false',
        'contact_acl'                        => 'true',
        'subscribe_context'                  => '',
        'fax_detect_timeout'                 => '0',
        'contact_user'                       => 'false',
        'preferred_codec_only'               => '0',
        'asymmetric_rtp_codec'               => 'false',
        'rtcp_mux'                           => 'false',
        'allow_overlap'                      => 'true',
        'refer_blind_progress'               => '',
        'notify_early_inuse_ringing'         => 'false',
        'max_audio_streams'                  => 'false',
        'max_video_streams'                  => 'false',
        'webrtc'                             => 'true',
        'dtls_fingerprint'                   => 'true',
        'incoming_mwi_mailbox'               => 'true',
        'bundle'                             => 'false',
        'dtls_auto_generate_cert'            => '1',
        'follow_early_media_fork'            => '1',
        'accept_multiple_sdp_answers'        => 'yes',
        'suppress_q850_reason_headers'       => 'SHA-256',
        'trust_connected_line'               => '',
        'send_connected_line'                => 'true',
        'ignore_183_without_sdp'             => 'no',
        'codec_prefs_incoming_offer'         => 'true',
        'codec_prefs_outgoing_offer'         => 'false',
        'codec_prefs_incoming_answer'        => 'true',
        'codec_prefs_outgoing_answer'        => 'false',
        'send_history_info'                  => 'yes',
        'allow_unauthenticated_options'      => 'yes',
        't38_bind_udptl_to_media_address'    => 'false',
        'geoloc_incoming_call_profile'       => 'prefer:pending, operation:intersect, keep:all, transcode:allow',
        'geoloc_outgoing_call_profile'       => 'prefer:pending, operation:union, keep:all, transcode:allow',
        'incoming_call_offer_pref'           => 'prefer:pending, operation:intersect, keep:all, transcode:allow',
        'outgoing_call_offer_pref'           => 'prefer:pending, operation:union, keep:all, transcode:allow',
        'stir_shaken_profile'                => 'false',
        'security_negotiation'               => 'false',
        'security_mechanisms'                => 'false',
        'send_aoc'                           => '',
        'overlap_context'                    => '',
        'tenantid'                           => 'local',
        'suppress_moh_on_sendonly'           => 'remote_merge',
    ];

    protected $keyType = 'int';
}
