name: tesis-app
region: atl

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

databases:
  - name: db-prod-laravel
    cluster_name: db-prod-laravel
    engine: MYSQL
    production: true
    db_name: laravel
    db_user: doadmin

# ===========================
# JOBS (PRE DEPLOY)
# ===========================
jobs:
  - name: db-migrate
    kind: PRE_DEPLOY
    github:
      repo: S3L1M26/ProyectoTitulo
      branch: main
      deploy_on_push: true
    dockerfile_path: WebRTCApp/Dockerfile
    source_dir: WebRTCApp
    instance_size_slug: basic-xs
    instance_count: 1
    run_command: |
      php -r 'for($i=0;$i<30;$i++){try{$pdo=new PDO("mysql:host=".getenv("DB_HOST").";port=".getenv("DB_PORT").";dbname=".getenv("DB_DATABASE").";charset=utf8mb4",getenv("DB_USERNAME"),getenv("DB_PASSWORD"),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);echo "db ready\n";exit(0);}catch(Throwable $e){echo "waiting DB...\n";sleep(2);} } echo "db unreachable\n"; exit(1);'
      php artisan migrate --force
    envs:
      - key: APP_NAME
        value: MentorMatch
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: ${APP_KEY}
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${db-prod-laravel.HOSTNAME}
      - key: DB_PORT
        value: ${db-prod-laravel.PORT}
      - key: DB_DATABASE
        value: ${db-prod-laravel.DATABASE}
      - key: DB_USERNAME
        value: ${db-prod-laravel.USERNAME}
      - key: DB_PASSWORD
        type: SECRET
        value: ${db-prod-laravel.PASSWORD}

  - name: scheduler
    kind: SCHEDULED
    schedule:
      cron: "*/15 * * * *"   # ejecuta cada minuto
    github:
      repo: S3L1M26/ProyectoTitulo
      branch: main
      deploy_on_push: true
    dockerfile_path: WebRTCApp/Dockerfile
    source_dir: WebRTCApp
    run_command: "php artisan schedule:run"
    envs:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: ${APP_KEY}
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${db-prod-laravel.HOSTNAME}
      - key: DB_PORT
        value: ${db-prod-laravel.PORT}
      - key: DB_DATABASE
        value: ${db-prod-laravel.DATABASE}
      - key: DB_USERNAME
        value: ${db-prod-laravel.USERNAME}
      - key: DB_PASSWORD
        type: SECRET
        value: ${db-prod-laravel.PASSWORD}
      - key: REDIS_HOST
        value: 129.212.187.206
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        type: SECRET
        value: ${REDIS_PASSWORD}
# ===========================
# WORKERS
# ===========================
workers:
  - name: queue
    github:
      repo: S3L1M26/ProyectoTitulo
      branch: main
      deploy_on_push: true
    dockerfile_path: WebRTCApp/Dockerfile
    source_dir: WebRTCApp
    run_command: |
      php artisan queue:work redis --queue=emails,default --sleep=3 --tries=3 --timeout=90 --verbose
    envs:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: ${APP_KEY}
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${db-prod-laravel.HOSTNAME}
      - key: DB_PORT
        value: ${db-prod-laravel.PORT}
      - key: DB_DATABASE
        value: ${db-prod-laravel.DATABASE}
      - key: DB_USERNAME
        value: ${db-prod-laravel.USERNAME}
      - key: DB_PASSWORD
        type: SECRET
        value: ${db-prod-laravel.PASSWORD}
      - key: REDIS_HOST
        value: 129.212.187.206
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        type: SECRET
        value: ${REDIS_PASSWORD}

# ===========================
# WEB SERVICE
# ===========================
services:
  - name: tesis-app
    github:
      repo: S3L1M26/ProyectoTitulo
      branch: main
      deploy_on_push: true
    dockerfile_path: WebRTCApp/Dockerfile
    source_dir: WebRTCApp
    http_port: 8000
    instance_size_slug: apps-s-1vcpu-1gb-fixed
    instance_count: 1

    envs:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: ${APP_KEY}
      - key: APP_URL
        value: https://tesis-app-4prsq.ondigitalocean.app
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${db-prod-laravel.HOSTNAME}
      - key: DB_PORT
        value: ${db-prod-laravel.PORT}
      - key: DB_DATABASE
        value: ${db-prod-laravel.DATABASE}
      - key: DB_USERNAME
        value: ${db-prod-laravel.USERNAME}
      - key: DB_PASSWORD
        type: SECRET
        value: ${db-prod-laravel.PASSWORD}
      - key: REDIS_HOST
        value: 129.212.187.206
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        type: SECRET
        value: ${REDIS_PASSWORD}
      - key: FILESYSTEM_DISK
        value: s3
      - key: AWS_ACCESS_KEY_ID
        value: ${AWS_ACCESS_KEY_ID}
      - key: AWS_SECRET_ACCESS_KEY
        type: SECRET
        value: ${AWS_SECRET_ACCESS_KEY}
      - key: AWS_DEFAULT_REGION
        value: atl1
      - key: AWS_BUCKET
        value: mentoria-space
      - key: AWS_ENDPOINT
        value: https://atl1.digitaloceanspaces.com
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: ${MAIL_USERNAME}
      - key: MAIL_PASSWORD
        type: SECRET
        value: ${MAIL_PASSWORD}
      - key: ZOOM_CLIENT_ID
        value: ${ZOOM_CLIENT_ID}
      - key: ZOOM_CLIENT_SECRET
        type: SECRET
        value: ${ZOOM_CLIENT_SECRET}
      - key: ZOOM_ACCOUNT_ID
        value: ${ZOOM_ACCOUNT_ID}
